apiVersion: v1
kind: Service
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    k8s-app: druid-broker
  name: {{ .Values.nodes.broker.service.name }}
  #TODO flexible service Name, configMap
  annotations:
    external-dns.alpha.kubernetes.io/hostname: druid-broker.aws2-vpc-ss-dts.savvybi.enterprises
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-2:547051082101:certificate/72dfd182-e87c-4b6b-803f-a12af7f1c4c0
spec:
  type: {{ .Values.nodes.broker.service.type }}
  ports:
    {{range .Values.nodes.broker.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
    {{end}}
    - name: https
      protocol: TCP
      port: 443
      targetPort: broker-port
    - name: http
      protocol: TCP
      port: 80
      targetPort: broker-port
  selector:
    #name: "{{ .Chart.Name }}-{{ .Values.nodes.broker.name }}-rc"
    k8s-app: druid-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.nodes.broker.name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      k8s-app: druid-broker
  replicas: {{ .Values.nodes.broker.replicaCount }}
  template:
    metadata:
      labels:
        name: "{{ .Chart.Name }}-{{ .Values.nodes.broker.name }}-rc"
        app: {{ template "fullname" . }}
        k8s-app: druid-broker
    spec:
      #hostname: broker
      #subdomain: druid
      containers:
      - name: "{{ .Chart.Name }}-{{ .Values.nodes.broker.name }}"
        image: "{{ .Values.nodes.broker.image.repository }}:{{ .Values.nodes.broker.image.tag }}"
        imagePullPolicy: {{ .Values.nodes.broker.image.pullPolicy }}
        volumeMounts:
          - name: config-volume
            mountPath: "/etc/druid/conf"

        #TODO add readiness & liveness probes
        #TODO reenable ressources here
        ports:
        {{range .Values.nodes.broker.service.ports }}
          - containerPort: {{ .port }}
        {{end}}

      volumes:
        - name: config-volume
          configMap:
            name: common-runtime-configmap
            items:
            - key: common.runtime.properties
              path: _common/common.runtime.properties
            - key: broker.runtime.properties
              path: broker/runtime.properties
            - key: broker.jvm.config
              path: broker/jvm.config
            - key: broker.main.config
              path: broker/main.config
