apiVersion: v1
kind: Service
metadata:

  #TODO flexible service Name, configMap
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    k8s-app: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ .Values.nodes.coordinator.service.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: druid-coordinator.aws2-vpc-ss-dts.savvybi.enterprises
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-2:547051082101:certificate/72dfd182-e87c-4b6b-803f-a12af7f1c4c0
spec:
  type: {{ .Values.nodes.coordinator.service.type }}
  ports:
    {{range .Values.nodes.coordinator.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
    {{end}}
    - name: https
      protocol: TCP
      port: 443
      targetPort: coordinator-port
    - name: http
      protocol: TCP
      port: 80
      targetPort: coordinator-port
  selector:
    #name: "{{ .Chart.Name }}-{{ .Values.nodes.coordinator.name }}-rc"
    k8s-app: "{{ .Chart.Name }}-{{ .Chart.Version }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.nodes.coordinator.name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      k8s-app: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  replicas: {{ .Values.nodes.coordinator.replicaCount }}
  template:
    metadata:
      labels:
        name: "{{ .Chart.Name }}-{{ .Values.nodes.coordinator.name }}-rc"
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: "{{ .Chart.Name }}-{{ .Values.nodes.coordinator.name }}"
        image: "{{ .Values.nodes.coordinator.image.repository }}:{{ .Values.nodes.coordinator.image.tag }}"
        imagePullPolicy: {{ .Values.nodes.coordinator.image.pullPolicy }}
        ports:
        {{range .Values.nodes.coordinator.service.ports }}
          - containerPort: {{ .port }}
        {{end}}
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/druid/conf"

        #TODO add readiness & liveness probes
      volumes:
        - name: config-volume
          configMap:
            name: common-runtime-configmap
            items:
            - key: common.runtime.properties
              path: _common/common.runtime.properties
            - key: coordinator.runtime.properties
              path: coordinator/runtime.properties
            - key: coordinator.jvm.config
              path: coordinator/jvm.config
            - key: coordinator.main.config
              path: coordinator/main.config
