apiVersion: v1
description: A Helm chart for running druid ontop of kubernetes, still work in progress.
name: druid-charts
version: 0.1.0
maintainers:
  - name: Kev Jackson
    email: foamdino@gmail.com
