dependencies:
- name: zookeeper
  version: 1.1.0
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
- name: postgresql
  version: 0.15.0
  repository: https://kubernetes-charts.storage.googleapis.com
