apiVersion: v1
kind: Service
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    k8s-app: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ .Values.nodes.overlord.service.name }}
  #TODO flexible service Name, configMap
  annotations:
    external-dns.alpha.kubernetes.io/hostname: druid-overlord.aws-vpc-ss-prod.savvybi.enterprises
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-2:547051082101:certificate/a4d61543-3163-4772-8f7a-39ef570dcf3a
spec:
  type: {{ .Values.nodes.overlord.service.type }}
  ports:
    {{range .Values.nodes.overlord.service.ports }}
    - name: overlord-port
      port: {{ .port }}
    {{end}}
    - name: https
      protocol: TCP
      port: 443
      targetPort: overlord-port
    - name: http
      protocol: TCP
      port: 80
      targetPort: overlord-port
  selector:
    #name: "{{ .Chart.Name }}-{{ .Values.nodes.overlord.name }}-rc"
    k8s-app: "{{ .Chart.Name }}-{{ .Chart.Version }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.nodes.overlord.name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      k8s-app: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  replicas: {{ .Values.nodes.overlord.replicaCount }}
  template:
    metadata:
      labels:
        name: "{{ .Chart.Name }}-{{ .Values.nodes.overlord.name }}-rc"
        app: {{ template "fullname" . }}
        k8s-app: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
      - name: "{{ .Chart.Name }}-{{ .Values.nodes.overlord.name }}"
        image: "{{ .Values.nodes.overlord.image.repository }}:{{ .Values.nodes.overlord.image.tag }}"
        imagePullPolicy: {{ .Values.nodes.overlord.image.pullPolicy }}
        ports:
        {{range .Values.nodes.overlord.service.ports }}
          - containerPort: {{ .port }}
        {{end}}
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/druid/conf"
        #TODO add readiness & liveness probes
      volumes:
        - name: config-volume
          configMap:
            name: common-runtime-configmap
            items:
            - key: common.runtime.properties
              path: _common/common.runtime.properties
            - key: overlord.runtime.properties
              path: overlord/runtime.properties
            - key: overlord.jvm.config
              path: overlord/jvm.config
            - key: overlord.main.config
              path: overlord/main.config
