---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.nodes.middlemanager.service.name }}
  labels:
    k8s-app: {{ .Values.nodes.middlemanager.service.name }}
spec:
  type: {{ .Values.nodes.middlemanager.service.type }}
  ports:
  {{range .Values.nodes.middlemanager.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
  {{end}}
  selector:
    k8s-app: {{ .Values.nodes.middlemanager.service.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nodes.middlemanager.service.name }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Values.nodes.middlemanager.service.name }}
  serviceName: {{ .Values.nodes.middlemanager.service.name }}
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.nodes.middlemanager.service.name }}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: druid-middlemanager
        image: 547051082101.dkr.ecr.ap-southeast-2.amazonaws.com/savvybi/druid-middlemanager:0.1
        imagePullPolicy: Always
        ports:
        {{range .Values.nodes.middlemanager.service.ports }}
          - containerPort: {{ .port }}
        {{end}}
        volumeMounts:
        - name: config-volume
          mountPath: "/iap-druid/{{ .Values.iapVersion }}/conf/druid/"
      volumes:
        - name: config-volume
          configMap:
            name: common-runtime-configmap
            items:
            - key: common.runtime.properties
              path: _common/common.runtime.properties
            - key: "{{ .Values.nodes.middlemanager.name }}.runtime.properties"
              path: middleManager/runtime.properties
            - key: "{{ .Values.nodes.middlemanager.name }}.jvm.config"
              path: middleManager/jvm.config
            - key: "{{ .Values.nodes.middlemanager.name }}.main.config"
              path: middleManager/main.config
